<?php

namespace Magento\Amazon\Test\Integration\Comm\Amazon;

use Magento\Amazon\Comm\Amazon\ApplyLogs;
use Magento\Amazon\Model\Amazon\AccountRepository;
use Magento\TestFramework\Helper\Bootstrap;
use PHPUnit\Framework\TestCase;

class ApplyLogsTest extends TestCase
{
    /**
     * @var \Magento\Framework\ObjectManagerInterface
     */
    private $objectManager;
    /**
     * @var ApplyLogs
     */
    private $applyLogs;
    /**
     * @var AccountRepository
     */
    private $accountRepository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->objectManager = Bootstrap::getObjectManager();
        $this->applyLogs = $this->objectManager->create(
            \Magento\Amazon\Comm\Amazon\ApplyLogs::class,
            ['batchSize' => 2]
        );
        $this->accountRepository = $this->objectManager->get(AccountRepository::class);
    }

    /**
     * @magentoDataFixture Magento_Amazon::Test/Integration/_files/indexer_amazon_account.php
     */
    public function testApplyRunsSuccessfullyWithoutLogs()
    {
        $account = $this->accountRepository->getAccountByName('mage-test');
        $this->applyLogs->apply($account);
    }
}
